# This file contains the fastlane.tools configuration
# For macOS App Store builds
# More information: https://docs.fastlane.tools

app_store_connect_api_key(
  key_id: "7FN57R567Z",
  issuer_id: "69a6de88-7946-47e3-e053-5b8c7c11a4d1",
  key_filepath: "/Users/smart/Projects/FlutterGimchi/fastlaneAuthKeys/AuthKey_7FN57R567Z.p8"
)

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the Mac App Store"
  lane :release do
    cocoapods(
      clean_install: true,
      repo_update: false,
      silent: false
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    
    # Build macOS app for App Store
    # Build macOS app for App Store
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "automatic",
        teamID: "NTCK5U8AWD"
      }
    )
    
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      precheck_include_in_app_purchases: false
    )
  end
end

